modLoader="javafml"
license="GPL License"
loaderVersion="[40,)"
displayURL="https://skeagle.net"
credits="Thanks to you for playing my mod!"
authors="Skeagle"

[[mods]]
modId="smodstuff"
version="${version}"
displayName="Skeagle's Mod Stuff"
description='''
I mean, it's literally just some stuff I've made...

What were you expecting?
'''

[[dependencies.smodstuff]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.smodstuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"