modLoader="javafml"
license="GPL License"
loaderVersion="[37,)"
displayURL="https://skeagle.net"
credits="Lexmanos and cpw"
authors="Skeagle"

[[mods]]
modId="smodstuff"
version="${version}"
displayName="Skeagle's Mod Stuff"
description='''
I mean, it's literally just some stuff I've made...

What were you expecting?
'''

[[dependencies.smodstuff]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.59,)"

[[dependencies.smodstuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,1.18)"
    ordering="NONE"
    side="BOTH"