modLoader="javafml"
license="GPL License"
loaderVersion="[36,)"
displayURL="https://skeagle.net"
credits="Lexmanos and cpw"
authors="Skeagle"

[[mods]]
modId="smodstuff"
version="${file.jarVersion}"
displayName="Skeagle's Mod Stuff"
description='''
I mean, it's literally just some stuff I've made...

What were you expecting?
'''

[[dependencies.smodstuff]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"